# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQerPcCtPpOn9EzH8NzGP9YVG7r59smy
"""

import pandas as pd

df=pd.DataFrame({"name":['sanju','virat','benarji','chintu'],
                 "age":['26','36','26','6'],
                 "height":['5','5.5','6','3']})

df

df["age"]

ages=pd.Series([26,36,26,6],name="ages")

ages

df["age"].max()

ages.max()

df.describe()

df.count()

df.min()

df.head()

df.tail()

df.info()

